input TestObjectInput {
  size: String
}

interface Node {
  id: ID!
}

interface RelayConnection {
  pageInfo: PageInfo!
}

interface RelayEdge {
  cursor: String!
}

type Mutation {
  createTestObject(input: TestObjectInput!): TestObject
  deleteTestObject(id: ID!): Boolean
  optionallyMutateTestObject(id: ID!, input: TestObjectInput!): TestObject #Tested
  updateTestObject(id: ID!, input: TestObjectInput!): TestObject
}

type PageInfo {
  endCursor: String
  hasNextPage: Boolean
  hasPreviousPage: Boolean
  startCursor: String
}

type Query {
  testContext: String #Tested
  testInterface: Node
  testInterfaceNonNull: Node!
  testObject(id: ID!): TestObject #Tested
  testObjectNonNull(id: ID!): TestObject! #Tested
  testObjects(size: String): [TestObject] #Tested
  testObjectsNonNull(size: String): [TestObject]! #Tested
  testObjectsNestedNonNull(size: String): [TestObject!]! #Tested
  testRelayConnection(
    color: String
    first: Int
    last: Int
    before: String
    after: String
  ): TestRelayConnection #Tested
  testNonNullEdgesRelayConnection(
    color: String
    first: Int
    last: Int
    before: String
    after: String
  ): TestNonNullEdgesRelayConnection #Tested
  testNonNullNodesRelayConnection(
    color: String
    first: Int
    last: Int
    before: String
    after: String
  ): TestNonNullNodesRelayConnection #Tested
  testScalar: String #Tested
  testScalarNonNull: String! #Tested
  testScalarOptionalResolve: String #Tested
  testSortedObjects: [TestObject] #Tested
  testUnion(oneName: String, twoName: String): [TestUnion] #Tested
  testUnionNonNull(oneName: String, twoName: String): [TestUnion]! #Tested
  testUnionNestedNonNull(oneName: String, twoName: String): [TestUnion!]! #Tested
}

type TestCategory {
  id: ID!
  name: String!
}

type TestObject {
  id: ID!
  belongsToField: TestCategory
  belongsToNonNullField: TestCategory!
  hasManyField: [TestOption]
  hasManyNonNullField: [TestOption]!
  hasManyNestedNonNullField: [TestOption!]!
  interfaceField: Node
  interfaceNonNullField: Node!
  relayConnectionField: TestRelayConnection
  relayConnectionNonNullField: TestRelayConnection!
  scalarField: String
  scalarNonNullField: String!
  size: String
  unionField: [TestUnion]
  unionNonNullField: [TestUnion]!
  unionNestedNonNullField: [TestUnion!]!
}

type TestNode implements Node {
  id: ID!
}

type TestOption {
  id: ID!
  name: String!
}

type TestRelayConnection implements RelayConnection {
  edges: [TestRelayEdge]
  pageInfo: PageInfo!
}

type TestNonNullEdgesRelayConnection implements RelayConnection {
  edges: [TestRelayEdge!]!
  pageInfo: PageInfo!
}

type TestNonNullNodesRelayConnection implements RelayConnection {
  edges: [TestNonNullNodesRelayEdge]
  pageInfo: PageInfo!
}

type TestRelayEdge implements RelayEdge {
  cursor: String!
  node: TestRelayNode
}

type TestNonNullNodesRelayEdge implements RelayEdge {
  cursor: String!
  node: TestRelayNode!
}

type TestRelayNode implements Node {
  id: ID!
  color: String
}

type TestUnionOne {
  id: ID!
  oneName: String
}

type TestUnionTwo {
  id: ID!
  twoName: String
}

union TestUnion = TestUnionOne | TestUnionTwo
